### PR TITLE
At your discretion: adding some of my projects :)

### PR DESCRIPTION
**Pull request by a-type**
I'm usually bad about self-promotion so I'm pushing myself a bit.

lo-fi - totally up to your consideration. I know lo-fi isn't really battle-tested yet, but I have been using it consistently for months in Gnocchi and it's working pretty well! It does both local-only schema-based storage (with migrations) and server-based sync.

For Gnocchi, though, I'm really happy with how far it's come and I think it's a good example of (at least my) philosophy for local-first web software. Most features work perfectly offline with no account, but you can upgrade to a server account to sync and access advanced features like multiplayer.

### CODE REVIEW

**Comment by a-type** [comment]
Huh, didn't know that would set the commit message. I'll amend it if you like.

**Review by jamesgpearce — CHANGES_REQUESTED** [review]
Thanks!

Happy to include both projects, but can you decide whether you want lofi in one list or the other?

(I realize maybe the store/sync distinction is fuzzy, but I don't want it to look like this commit spams them both :) )

**Comment by a-type** [comment]
Yup, that's no problem. I guess I'll go with sync since that's the more interesting one.

**Comment by a-type** [comment]
Updated!

**Review by jamesgpearce — APPROVED** [review]
<3

**Comment by jamesgpearce** [comment]
It has an icon so I moved it to the top of the list

**Pull request merged**
